# Generated by Django 4.2.1 on 2023-06-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Placeholder', max_length=300),
            preserve_default=False,
        ),
    ]
